#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "forgejo_runner"
name = "Forgejo Runner"
description.en = "CI Runner for the Git forge Forgejo"
description.fr = "Exécuteur CI pour la forge Git Forgejo"

version = "11.3.0~ynh1"

maintainers = ["salamandar"]

[upstream]
license = "MIT"
website = "https://forgejo.org"
demo = "https://code.forgejo.org"
admindoc = "https://forgejo.org/docs/latest/admin/runner-installation/"
userdoc = "https://forgejo.org/docs/latest/user/actions/#forgejo-runner"
code = "https://code.forgejo.org/forgejo/runner"

[integration]
yunohost = '>= 12.1.17'
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = "not_relevant"
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.forge_url]
    ask.en = "The URL to your Forgejo server"
    ask.fr = "L'adresse de votre serveur Forgejo"
    type = "string"
    example = "https://code.forgejo.org"

    [install.registration_token]
    ask.en = "The registration token provided by your Forgejo server"
    ask.fr = "Le jeton d'inscription fourni par votre serveur Forgejo"
    type = "string"

    [install.runner_name]
    ask.en = "The runner's name visible on the forge"
    ask.fr = "Le nom de l'exécuteur visible sur la forge"
    type = "string"

    [install.runner_labels]
    ask.en = "The runner's labels (comma-separated list)"
    ask.fr = "Les labels de l'exécuteur (liste séparée par des virgules)"
    type = "string"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://code.forgejo.org/forgejo/runner/releases/download/v11.3.0/forgejo-runner-11.3.0-linux-amd64"
    amd64.sha256 = "f8fdba097e622d90d71f85fb3118dd1bfc095a3215d78499f4a61934165e2ee4"
    arm64.url = "https://code.forgejo.org/forgejo/runner/releases/download/v11.3.0/forgejo-runner-11.3.0-linux-arm64"
    arm64.sha256 = "1d41ac48f7086f5547fa851db5cdc524c23ce9b3115393ec2610c7c46470c905"
    rename = "forgejo-runner"

    autoupdate.strategy = "latest_forgejo_release"
    autoupdate.asset.amd64 = "^forgejo-runner-.*-linux-amd64$"
    autoupdate.asset.arm64 = "^forgejo-runner-.*-linux-arm64$"

    [resources.system_user]

    [resources.install_dir]

    [resources.ports]
