#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "forgejo_runner"
name = "Forgejo Runner"
description.en = "CI Runner for the Git forge Forgejo"
description.fr = "Exécuteur CI pour la forge Git Forgejo"

version = "12.1.1~ynh1"

maintainers = ["salamandar"]

[upstream]
license = "MIT"
website = "https://forgejo.org"
demo = "https://code.forgejo.org"
admindoc = "https://forgejo.org/docs/latest/admin/runner-installation/"
userdoc = "https://forgejo.org/docs/latest/user/actions/#forgejo-runner"
code = "https://code.forgejo.org/forgejo/runner"

[integration]
yunohost = '>= 12.1.17'
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = "not_relevant"
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.forge_url]
    ask.en = "The URL to your Forgejo server"
    ask.fr = "L'adresse de votre serveur Forgejo"
    type = "string"
    example = "https://code.forgejo.org"

    [install.registration_token]
    ask.en = "The registration token provided by your Forgejo server"
    ask.fr = "Le jeton d'inscription fourni par votre serveur Forgejo"
    type = "string"

    [install.runner_name]
    ask.en = "The runner's name visible on the forge"
    ask.fr = "Le nom de l'exécuteur visible sur la forge"
    type = "string"

    [install.runner_labels]
    ask.en = "The runner's labels (comma-separated list)"
    ask.fr = "Les labels de l'exécuteur (liste séparée par des virgules)"
    type = "string"

[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://code.forgejo.org/forgejo/runner/releases/download/v12.1.1/forgejo-runner-12.1.1-linux-amd64"
    amd64.sha256 = "ac41051eedcf1e6c2212fc87b23d9a979311b7edbd94f2df0b559894d67b5122"
    arm64.url = "https://code.forgejo.org/forgejo/runner/releases/download/v12.1.1/forgejo-runner-12.1.1-linux-arm64"
    arm64.sha256 = "3df51bb1bb3a621adc57990ba96aab9f6d7733fde12e47a3f7d3865b596376b5"
    rename = "forgejo-runner"

    autoupdate.strategy = "latest_forgejo_release"
    autoupdate.asset.amd64 = "^forgejo-runner-.*-linux-amd64$"
    autoupdate.asset.arm64 = "^forgejo-runner-.*-linux-arm64$"

    [resources.system_user]

    [resources.install_dir]

    [resources.ports]
