#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "forgejo_runner"
name = "Forgejo Runner"
description.en = "CI Runner for the Git forge Forgejo"
description.fr = "Exécuteur CI pour la forge Git Forgejo"

version = "12.11.0~ynh1"

maintainers = ["salamandar"]

[upstream]
license = "MIT"
website = "https://forgejo.org"
demo = "https://code.forgejo.org"
admindoc = "https://forgejo.org/docs/latest/admin/runner-installation/"
userdoc = "https://forgejo.org/docs/latest/user/actions/#forgejo-runner"
code = "https://code.forgejo.org/forgejo/runner"

[integration]
yunohost = '>= 12.1.38'
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = "not_relevant"
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.local_forge]
    ask.en = "Do you want to link it to a local forgejo server?"
    ask.fr = "Est-ce pour le lier à un serveur forgejo local?"
    type = "boolean"
    yes = "1"
    no = "0"
    default = "true"

    [install.forgejo_app]
    ask.en = "Name of the local forgejo instance you want to link to"
    ask.fr = "Nom de l'instance locale de forgejo que vous voulez lier"
    type = "string"
    default = "forgejo"
    visible = "local_forge"

    [install.forge_url]
    ask.en = "The URL to your Forgejo server"
    ask.fr = "L'adresse de votre serveur Forgejo"
    type = "string"
    example = "https://code.forgejo.org"
    visible = '! local_forge'
    
    [install.registration_token]
    ask.en = "The registration token provided by your Forgejo server"
    ask.fr = "Le jeton d'inscription fourni par votre serveur Forgejo"
    type = "string"
    visible = '! local_forge'
    
    [install.runner_name]
    ask.en = "The runner's name visible on the forge"
    ask.fr = "Le nom de l'exécuteur visible sur la forge"
    type = "string"
    visible = '! local_forge'
    
    [install.runner_labels]
    ask.en = "The runner's labels (comma-separated list)"
    ask.fr = "Les labels de l'exécuteur (liste séparée par des virgules)"
    type = "string"
    default = "self-hosted:host"
    help.en = "They should be written as follows, change <label-name> : <label-name1>:host,<label-name2>:host"
    help.fr = "Ils doivent s'écrire sous la forme suivante en changeant <label-name> : <label-name1>:host,<label-name2>:host"
    
[resources]

    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://code.forgejo.org/forgejo/runner/releases/download/v12.11.0/forgejo-runner-12.11.0-linux-amd64"
    amd64.sha256 = "867ab02b3e2801267764c0fd10b9f17890975fc0d41f20b8274e9d0a1cd93dd4"
    arm64.url = "https://code.forgejo.org/forgejo/runner/releases/download/v12.11.0/forgejo-runner-12.11.0-linux-arm64"
    arm64.sha256 = "2c4d3b05c89b56432d8b4be5ac91118515c9bf54aa68475064e0187e4b862816"
    rename = "forgejo-runner"

    autoupdate.strategy = "latest_forgejo_release"
    autoupdate.asset.amd64 = "^forgejo-runner-.*-linux-amd64$"
    autoupdate.asset.arm64 = "^forgejo-runner-.*-linux-arm64$"

    [resources.system_user]

    [resources.install_dir]

    [resources.ports]
