#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    preinstall = """
    sudo yunohost tools update apps
    sudo yunohost app install forgejo --force --args "domain=sub.domain.tld&path=/&init_main_permission=visitors&init_admin_permission=admins"
    """

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.forge_url = "https://sub.domain.tld/"
    args.registration_token = "123456"
    args.runner_name = "forge_runner"
    args.runner_labels = "runner"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------
