#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    args.forge_url = "https://code.forgejo.org"
    args.registration_token = "123456"
    args.runner_name = "forge_runner"
    args.runner_labels = "runner"
