#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

chmod +x "$install_dir/forgejo-runner"
chown -R "$app:www-data" "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated systemd config
ynh_config_add_systemd

yunohost service add "$app" --description="Forgejo Runner" --log="/var/log/$app/$app.log"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Installing $app..."

ynh_config_add --jinja --template="config.yml" --destination="$install_dir/config.yml"

if [ "${PACKAGE_CHECK_EXEC:-0}" -eq 1 ]; then
    # Ask Forgejo to generate a registration token
    registration_token=$(sudo -u forgejo /var/www/forgejo/forgejo actions generate-runner-token)
    ynh_app_setting_set --key="registration_token" --value="$registration_token"

    # Communication should be local to prevent ssl issues
    # url="http://127.0.0.1:$(ynh_app_setting_get --app="forgejo" --key="port")/"
    # ynh_app_setting_set --key="forge_url" --value="$url"

    export insecure=true
fi

if [ "$local_forge" -eq 1 ]; then
    # Ask local Forgejo to generate a registration token
    registration_token=$(sudo -u $forgejo_app /var/www/$forgejo_app/forgejo actions generate-runner-token)
    ynh_app_setting_set --key="registration_token" --value="$registration_token"

    runner_name="ynh_local_runner"
    ynh_app_setting_set --key="runner_name" --value="$runner_name"

    url=$(ynh_app_setting_get --app="$forgejo_app" --key="domain")
    forge_url="https://$url"
    ynh_app_setting_set --key="forge_url" --value="$forge_url"
fi

pushd "$install_dir"
    ynh_hide_warnings ynh_exec_as_app "$install_dir/forgejo-runner" register \
        --config "$install_dir/config.yml" \
        --no-interactive \
        --instance "$forge_url" \
        --name "$runner_name" \
        --token "$registration_token"
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start" --wait_until="launched" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
