#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"
chmod +x "$install_dir/forgejo-runner"
chown -R "$app:www-data" "$install_dir"

if [ "${PACKAGE_CHECK_EXEC:-0}" -eq 1 ]; then
    # Ask Forgejo to generate a registration token
    registration_token=$(sudo -u forgejo /var/www/forgejo/forgejo actions generate-runner-token)
    ynh_app_setting_set --key="registration_token" --value="$registration_token"

    runner_name="ynh_local_runner"
    ynh_app_setting_set --key="runner_name" --value="$runner_name"

    url=$(ynh_app_setting_get --app="$forgejo_app" --key="domain")
    forge_url="https://$url"
    ynh_app_setting_set --key="forge_url" --value="$forge_url"

    pushd "$install_dir"
        ynh_hide_warnings ynh_exec_as_app "$install_dir/forgejo-runner" register \
            --config "$install_dir/config.yml" \
            --no-interactive \
            --instance "$forge_url" \
            --name "$runner_name" \
            --token "$registration_token"
    popd
fi

#=================================================
# RESTORE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet

yunohost service add "$app" --description="Forgejo Runner" --log="/var/log/$app/$app.log"

mkdir -p "/var/log/$app"
chown -R "$app:$app" "/var/log/$app"
ynh_restore "/etc/logrotate.d/$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app" --action="start" --wait_until="launched" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
