#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

if [ ${PACKAGE_CHECK_EXEC:-0} -eq 1 ]; then
	registration_token=$(ynh_string_random --length=40 --filter="0-9a-f")
	sudo -u forgejo env PATH="$PATH" /var/www/forgejo/forgejo forgejo-cli actions register --secret $registration_token
	forge_url="http://127.0.0.1:$(ynh_app_setting_get --app="forgejo" --key="port")/"
	pushd "$install_dir"
		ynh_hide_warnings ynh_exec_as_app "$install_dir/forgejo-runner" create-runner-file --connect --instance $forge_url --secret $registration_token --name $runner_name
	popd
fi

#=================================================
# RESTORE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet
yunohost service add "$app" --description="Forgejo Runner" --log="/var/log/$app/$app.log"

mkdir -p /var/log/$app
chown -R $app:$app /var/log/$app
ynh_restore "/etc/logrotate.d/$app"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app" --action="start" --wait_until="launched" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
